#!/usr/bin/env python3
"""make_osk_font.py -- rasterize the OSK font atlas + generate the single
source of truth for the 0.95.8 OSK overhaul (charcoal + blue accent, grid
layout, DejaVu Sans Bold per user picks).

Outputs:
  ports/gamedevstory/gamedevstory/osk_font.rgba  (320x320 RGBA atlas, runtime-loaded)
  loader_ref/osk_font_data.h                     (advances + metrics, compiled in)
  loader_ref/osk_layout.h                        (palette + panel + key tables, compiled in)
  mock_osk.png                                   (preview of the final look for the user)

Design notes: the key tables drive BOTH the C draw and the mock, so they can
never drift apart.  Palette: charcoal panel with a subtle top->bottom
gradient, soft 3D-beveled keys, one calm blue accent (user pick).
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_RGBA = os.path.join(ROOT, 'ports/gamedevstory/gamedevstory/osk_font.rgba')
OUT_FONTH = os.path.join(ROOT, 'loader_ref/osk_font_data.h')
OUT_LAY = os.path.join(ROOT, 'loader_ref/osk_layout.h')
OUT_MOCK = os.path.join(ROOT, 'mock_osk.png')

TTF = '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'
PX = 24            # nominal glyph px in the atlas (24 keeps tall glyphs inside 32px cells)
CELL = 32          # atlas cell
COLS, ROWS = 10, 9  # 95 glyphs 0x20..0x7E -> 10 cols; 9.5 rows -> use 10 rows w/ last cells blank
AW = COLS * CELL
AH = 10 * CELL

# ---------------------------------------------------------------- layout (640x480)
ACT_CHAR, ACT_SHIFT, ACT_SYM, ACT_SPACE, ACT_BKSP, ACT_DONE = range(6)

L = {}
L['panel'] = (30, 34, 580, 416)                    # x, y, w, h
L['bands'] = [                                     # top->bottom charcoal gradient
    (0x3b, 0x43, 0x53), (0x34, 0x3b, 0x49),
    (0x2d, 0x33, 0x3f), (0x26, 0x2b, 0x35)]
L['panel_hi'] = (0x58, 0x62, 0x82)                 # top highlight line
L['panel_lo'] = (0x17, 0x1a, 0x21)                 # bottom shadow line
L['title_c'] = (0xe8, 0xec, 0xf4)
L['dim_c'] = (0x9a, 0xa3, 0xb5)
L['hint_c'] = (0x8f, 0x98, 0xab)
L['box_border'] = (0x14, 0x17, 0x20)
L['box_fill'] = (0x1b, 0x1e, 0x26)
L['text_c'] = (0xf4, 0xf6, 0xfa)
L['accent'] = (0x6e, 0xa8, 0xff)                   # calm blue (caret etc.)
L['sel_face'] = (0x3d, 0x7b, 0xff)
L['sel_edge'] = (0x9d, 0xc1, 0xff)
L['key_face'] = (0x45, 0x4d, 0x60)
L['key_edge'] = (0x5b, 0x64, 0x79)
L['key_lo'] = (0x17, 0x1a, 0x21)                   # bottom bevel shadow
L['fn_face'] = (0x3a, 0x41, 0x52)
L['done_face'] = (0x2e, 0x63, 0xc8)
L['done_edge'] = (0x6f, 0x9f, 0xe8)
L['shift_face'] = (0x2f, 0x5d, 0xb8)
L['textbox'] = (56, 84, 528, 42)                   # x,y,w,h (border incl.)
L['title_pos'] = (58, 46)
L['hint_pos'] = (60, 420)
L['counter_y'] = 50

KX0, KW, KGAP, KH, VGAP = 57, 50, 3, 48, 8
ROWY = [142, 198, 254, 310]

letters_rows = [
    "1234567890",
    "qwertyuiop",
    "asdfghjkl",
    "zxcvbnm",
]
sym_rows = [
    "1234567890",
    "!@#$%^&*()",
    "-_=+[]{};:",
    "'\",./\\|~<>",
]

FN_Y = 366
fn_keys = [   # label, x, y, w, action
    ("SHIFT", 60, FN_Y, 86, ACT_SHIFT),
    ("SYM",    149, FN_Y, 66, ACT_SYM),
    ("SPACE",  218, FN_Y, 180, ACT_SPACE),
    ("DEL",    401, FN_Y, 66, ACT_BKSP),
    ("DONE",   470, FN_Y, 111, ACT_DONE),
]
HINT = "A TYPE  B DEL  X SHIFT  Y SPACE  L1/R1 PAGE  SEL CANCEL  START DONE"
HINT_SCALE = 0.48   # fits the full hint inside the panel (x centered in C)

# ---------------------------------------------------------------- font atlas
def build_atlas():
    font = ImageFont.truetype(TTF, PX)
    asc, desc = font.getmetrics()
    top_pad = 3
    atlas = Image.new('RGBA', (AW, AH), (255, 255, 255, 0))
    dr = ImageDraw.Draw(atlas)
    adv = [0.0] * 96
    for ci, cp in enumerate(range(0x20, 0x7F)):
        c = chr(cp)
        col, row = ci % COLS, ci // COLS
        ox, oy = col * CELL, row * CELL
        if c != ' ':
            dr.text((ox + 1, oy + top_pad), c, font=font, fill=(255, 255, 255, 255))
        adv[ci] = font.getlength(c)
        bb = font.getbbox(c)
        if c != ' ' and (bb[3] + top_pad > CELL or bb[2] + 1 > CELL):
            print(f"WARN: glyph {c!r} bbox {bb} exceeds cell")
    order = [(i % COLS) * CELL + (i // COLS) * CELL * AW for i in range(95)]
    rgba = atlas.tobytes()
    os.makedirs(os.path.dirname(OUT_RGBA), exist_ok=True)
    with open(OUT_RGBA, 'wb') as f:
        f.write(rgba)
    space_w = font.getlength('n') * 0.62 + font.getlength(' ')  # sane fallback
    return asc, desc, top_pad, adv, space_w

# ---------------------------------------------------------------- header emit
def fl(c):
    return "%.5ff, %.5ff, %.5ff" % (c[0] / 255, c[1] / 255, c[2] / 255)

def emit_font_h(asc, top_pad, adv, space_w):
    with open(OUT_FONTH, 'w') as f:
        f.write("/* generated by tools/make_osk_font.py -- do not edit by hand */\n")
        f.write("#define OVK_AW %d\n#define OVK_AH %d\n#define OVK_CELL %d\n"
                "#define OVK_COLS %d\n#define OVK_ASC_CELL %.1ff   /* cell-origin to baseline */\n"
                "#define OVK_PX %d\n#define OVK_SPACE_W %.3ff\n" %
                (AW, AH, CELL, COLS, top_pad + asc, PX, space_w))
        f.write("static const float ovk_adv[96] = {\n")
        for i in range(0, 96, 8):
            f.write("    " + ", ".join("%.3ff" % a for a in adv[i:i + 8]) + ",\n")
        f.write("};\n")

def emit_key(f, label, x, y, w, h, lo, hi, act):
    # C-escape every field: lo/hi go in single quotes, label in double.
    lab = label.replace('\\', '\\\\').replace('"', '\\"')
    f.write('    { %d, %d, %d, %d, \'%s\', \'%s\', %s, "%s" },\n' %
            (x, y, w, h, lo.replace('\\', '\\\\').replace("'", "\\'"),
             hi.replace('\\', '\\\\').replace("'", "\\'"),
             "OVKA_" + {ACT_CHAR: 'CHAR', ACT_SHIFT: 'SHIFT', ACT_SYM: 'SYM',
                        ACT_SPACE: 'SPACE', ACT_BKSP: 'BKSP', ACT_DONE: 'DONE'}[act],
             lab))

def emit_layout_h():
    with open(OUT_LAY, 'w') as f:
        f.write("/* generated by tools/make_osk_font.py -- do not edit by hand */\n")
        f.write("enum { OVKA_CHAR, OVKA_SHIFT, OVKA_SYM, OVKA_SPACE, OVKA_BKSP, OVKA_DONE };\n")
        f.write("typedef struct { short x, y, w, h; char lo, hi; unsigned char act; const char *label; } ovk_key_t;\n")
        for name, c in L.items():
            if isinstance(c, tuple) and len(c) == 3:
                f.write("#define OVKC_%-10s %s\n" % (name.upper(), fl(c)))
        px, py, pw, ph = L['panel']
        f.write("#define OVK_PANEL %d, %d, %d, %d\n" % (px, py, pw, ph))
        f.write("static const float ovk_bands[4][3] = { " +
                ", ".join("{ %s }" % fl(b) for b in L['bands']) + " };\n")
        bx, by, bw, bh = L['textbox']
        f.write("#define OVK_BOX %d, %d, %d, %d\n" % (bx, by, bw, bh))
        tx, ty = L['title_pos']
        f.write("#define OVK_TITLE_POS %d, %d\n#define OVK_COUNTER_Y %d\n"
                % (tx, ty, L['counter_y']))
        hx, hy = L['hint_pos']
        f.write("#define OVK_HINT_POS %d, %d\n#define OVK_HINT \"%s\"\n" % (hx, hy, HINT))
        for tname, table in (("letters", letters_rows), ("symbols", sym_rows)):
            keys = []
            for ri, row in enumerate(table):
                for ci, c in enumerate(row):
                    keys.append((c, KX0 + ci * (KW + KGAP), ROWY[ri], KW, KH,
                                 c if c != ' ' else ' ', c.upper() if c.isalpha() else c))
            f.write("static const ovk_key_t ovk_%s[] = {\n" % tname)
            for c, x, y, w, h, lo, hi in keys:
                emit_key(f, c, x, y, w, h, lo, hi, ACT_CHAR)
            f.write("};\n")
        f.write("static const ovk_key_t ovk_func[] = {\n")
        for lab, x, y, w, act in fn_keys:
            f.write('    { %d, %d, %d, %d, 0, 0, %s, "%s" },\n' %
                    (x, y, w, KH,
                     {ACT_SHIFT: 'OVKA_SHIFT', ACT_SYM: 'OVKA_SYM',
                      ACT_SPACE: 'OVKA_SPACE', ACT_BKSP: 'OVKA_BKSP',
                      ACT_DONE: 'OVKA_DONE'}[act], lab))
        f.write("};\n")
        f.write("#define OVK_N_LETTERS %d\n#define OVK_N_SYMBOLS %d\n#define OVK_N_FUNC %d\n"
                % (sum(len(r) for r in letters_rows), sum(len(r) for r in sym_rows),
                   len(fn_keys)))

# ---------------------------------------------------------------- mock preview
def mock(asc, top_pad):
    font = ImageFont.truetype(TTF, PX)
    S = 2  # draw at 2x
    im = Image.new('RGB', (640 * S, 480 * S), (0x4c, 0x73, 0xe2))  # game-ish bg
    dr = ImageDraw.Draw(im)
    def rr(x, y, w, h, c):
        dr.rectangle([x * S, y * S, (x + w) * S - 1, (y + h) * S - 1], fill=c)
    # scrim
    ov = Image.new('RGBA', im.size, (0, 0, 0, 0))
    ImageDraw.Draw(ov).rectangle([0, 0, im.size[0] - 1, im.size[1] - 1],
                                 fill=(0, 0, 0, int(0.55 * 255)))
    im = Image.alpha_composite(im.convert('RGBA'), ov).convert('RGB')
    dr = ImageDraw.Draw(im)
    px, py, pw, ph = L['panel']
    bh = ph // 4
    for i, b in enumerate(L['bands']):
        rr(px, py + i * bh, pw, bh + (ph - 4 * bh if i == 3 else 0), b)
    rr(px, py, pw, 2, L['panel_hi'])
    rr(px, py + ph - 2, pw, 2, L['panel_lo'])
    def text(x, y_baseline, s, c, scale=1.0):
        pen = x
        for ch in s:
            a = font.getlength(ch) * scale
            if ch != ' ':
                # draw glyph cell: mock renders straight with scale
                f2 = font if scale == 1.0 else ImageFont.truetype(TTF, max(6, int(PX * scale)))
                dr.text((pen * S, (y_baseline - (top_pad + asc) * scale) * S), ch,
                        font=f2, fill=c)
            pen += a
        return pen
    tx, ty = L['title_pos']
    text(tx, ty + 22, "COMPANY NAME", L['title_c'], 0.75)
    text(500, L['counter_y'] + 22, "13/14", L['dim_c'], 0.58)
    bx, by, bw, bh = L['textbox']
    rr(bx, by, bw, bh, L['box_border'])
    rr(bx + 2, by + 2, bw - 4, bh - 4, L['box_fill'])
    t = "Sunny Studios"
    endx = text(bx + 10, by + 30, t, L['text_c'], 0.846)
    rr(int(endx) + 2, by + 8, 3, 26, L['accent'])
    sel = (1, 5)   # highlight 'g' row2 idx5? use row1 idx5 -> 'y'; pick (2,5)='g'
    for vi, table in enumerate((letters_rows,)):
        for ri, row in enumerate(table):
            for ci, c in enumerate(row):
                x, y = KX0 + ci * (KW + KGAP), ROWY[ri]
                is_sel = (ri, ci) == sel
                face = L['sel_face'] if is_sel else L['key_face']
                edge = L['sel_edge'] if is_sel else L['key_edge']
                if is_sel:
                    dr.rectangle([(x - 2) * S, (y - 2) * S, (x + KW + 1) * S, (y + KH + 1) * S],
                                 fill=(0x2b, 0x4f, 0xa8))
                rr(x, y + 3, KW, KH - 1, L['key_lo'])
                rr(x, y, KW, KH - 2, face)
                rr(x, y, KW, 2, edge)
                wpx = font.getlength(c) * 0.85
                text(x + (KW - wpx) / 2, y + KH / 2 + 8, c, L['text_c'], 0.85)
    for lab, x, y, w, act in fn_keys:
        face = L['done_face'] if act == ACT_DONE else L['fn_face']
        edge = L['done_edge'] if act == ACT_DONE else L['key_edge']
        rr(x, y + 3, w, KH - 1, L['key_lo'])
        rr(x, y, w, KH - 2, face)
        rr(x, y, w, 2, edge)
        f2 = ImageFont.truetype(TTF, 15)
        tw = dr.textlength(lab, font=f2)
        dr.text(((x + (w - tw / S) / 2) * S, (y + KH / 2 - 7) * S), lab, font=f2,
                fill=L['text_c'])
    hx, hy = L['hint_pos']
    f3 = ImageFont.truetype(TTF, 13)
    dr.text((hx * S, hy * S), HINT, font=f3, fill=L['hint_c'])
    im = im.resize((640, 480))
    im.save(OUT_MOCK)
    print("mock:", OUT_MOCK)

def main():
    asc, desc, top_pad, adv, space_w = build_atlas()
    print("atlas:", OUT_RGBA, "asc=%d desc=%d" % (asc, desc))
    emit_font_h(asc, top_pad, adv, space_w)
    emit_layout_h()
    print("headers:", OUT_FONTH, "and", OUT_LAY)
    mock(asc, top_pad)

if __name__ == '__main__':
    main()
