#!/usr/bin/env bash
# =============================================================================
# build.sh -- Epic Astro Story : Android APK  ->  browser build
#
#   base64.txt / *.apk
#        |  (1) base64 -d + unzip
#        v
#   build/apk/classes.dex ------ (2) tools/dex2js.py ----> web/dex/*.js
#   build/apk/assets/*.dat ----- (3) copy -----------------> web/assets/
#   build/apk/res/raw/* -------- (3) copy -----------------> web/raw/
#        |
#        +-- (4) manifest.json + index.html + runtime concat -> web/
#
# The DEX is *recompiled*, not re-implemented: every class / method /
# instruction of the shipped application is translated 1:1 to JavaScript.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

BUILD="$ROOT/build"
WEB="$ROOT/web"
APKDIR="$BUILD/apk"
APK="$BUILD/app.apk"

say() { printf '\033[36m[build]\033[0m %s\n' "$*"; }

# --------------------------------------------------------------- 1. unpack
say "stage 1/5  unpack APK"
mkdir -p "$BUILD"

if [ -f "$ROOT/base64.txt" ]; then
    say "  decoding base64.txt"
    tr -d '\r\n' < "$ROOT/base64.txt" | base64 -d > "$APK"
else
    src="$(ls -1 "$ROOT"/*.apk 2>/dev/null | head -n1 || true)"
    [ -n "$src" ] || { echo "no base64.txt and no .apk in $ROOT" >&2; exit 1; }
    say "  using $src"
    cp "$src" "$APK"
fi

# sanity: the archive must be a real APK carrying a DEX
unzip -l "$APK" | grep -q 'classes\.dex' \
    || { echo "payload is not an APK (no classes.dex)" >&2; exit 1; }

rm -rf "$APKDIR"
mkdir -p "$APKDIR"
unzip -qo "$APK" -d "$APKDIR"
say "  sha256 $(sha256sum "$APK" | cut -c1-16)...  dex $(stat -c%s "$APKDIR/classes.dex") bytes"

# ------------------------------------------------------------- 2. recompile
say "stage 2/5  recompile Dalvik bytecode -> JavaScript"
rm -rf "$WEB/dex"
mkdir -p "$WEB/dex"
python3 tools/dex2js.py "$APKDIR/classes.dex" -o "$WEB/dex"

# ---------------------------------------------------------------- 3. payload
say "stage 3/5  copy game payload"
rm -rf "$WEB/assets" "$WEB/raw"
mkdir -p "$WEB/assets" "$WEB/raw"
cp -a "$APKDIR/assets/." "$WEB/assets/" 2>/dev/null || true
cp -a "$APKDIR/res/raw/." "$WEB/raw/"   2>/dev/null || true

python3 - "$WEB" <<'PY'
import json, os, sys
web = sys.argv[1]
def listing(d):
    p = os.path.join(web, d)
    if not os.path.isdir(p):
        return []
    return sorted(f for f in os.listdir(p) if os.path.isfile(os.path.join(p, f)))
man = {"assets": [f for f in listing("assets") if f != "manifest.json"],
       "raw": listing("raw")}
with open(os.path.join(web, "assets", "manifest.json"), "w") as f:
    json.dump(man, f, indent=1)
print("[build]   assets: %d   raw: %d" % (len(man["assets"]), len(man["raw"])))
PY

# ---------------------------------------------------------------- 4. runtime
say "stage 4/5  link runtime"
RUNTIME_ORDER=(00-core 01-host 05-image 10-lang 20-util 25-io 30-graphics \
               35-android-content 40-android-view 45-android-os \
               50-android-media)
BOOT_ORDER=(55-licensing 60-boot)

{
  echo "/* Epic Astro Story -- Java/Android runtime for the recompiled DEX."
  echo " * Generated by build.sh; edit the sources in runtime/ instead. */"
  for f in "${RUNTIME_ORDER[@]}"; do
      echo ""
      echo "/* ==== runtime/$f.js ==================================== */"
      cat "runtime/$f.js"
  done
} > "$WEB/runtime.js"

{
  echo "/* Epic Astro Story -- platform bridge + boot (generated by build.sh) */"
  for f in "${BOOT_ORDER[@]}"; do
      echo ""
      echo "/* ==== runtime/$f.js ==================================== */"
      cat "runtime/$f.js"
  done
} > "$WEB/boot.js"

# ------------------------------------------------------------------ 5. shell
say "stage 5/5  emit web/index.html"
cat > "$WEB/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="theme-color" content="#0b0d12">
<title>Epic Astro Story</title>
<link rel="icon" href="data:,">
</head>
<body>
<!-- load order matters:
     dex-meta   defines $DEXMETA, read by the runtime's name mangler
     runtime    java.* / android.* implemented on top of the browser
     dex-classes the recompiled application (needs every runtime class)
     boot       licence patch + DOM bridge + scheduler pump            -->
<script src="dex/dex-meta.js"></script>
<script src="runtime.js"></script>
<script src="dex/dex-classes.js"></script>
<script src="boot.js"></script>
<script>$EAS.boot();</script>
</body>
</html>
HTML

say "done -> $WEB"
say "serve:  python3 -m http.server -d web 8080"
