/* generated by tools/make_osk_font.py -- do not edit by hand */
enum { OVKA_CHAR, OVKA_SHIFT, OVKA_SYM, OVKA_SPACE, OVKA_BKSP, OVKA_DONE };
typedef struct { short x, y, w, h; char lo, hi; unsigned char act; const char *label; } ovk_key_t;
#define OVKC_PANEL_TOP  0.18039f, 0.18039f, 0.20392f
#define OVKC_PANEL_BOT  0.07843f, 0.07843f, 0.09412f
#define OVKC_PANEL_HI   0.33333f, 0.33333f, 0.37255f
#define OVKC_PANEL_LO   0.04314f, 0.04314f, 0.05490f
#define OVKC_TITLE_C    0.85490f, 0.85490f, 0.87843f
#define OVKC_DIM_C      0.64314f, 0.64314f, 0.67059f
#define OVKC_BOX_BORDER 0.03922f, 0.03922f, 0.04706f
#define OVKC_BOX_FILL   0.07059f, 0.07059f, 0.08235f
#define OVKC_TEXT_C     0.95686f, 0.95686f, 0.96471f
#define OVKC_SEL_FACE   0.88627f, 0.88627f, 0.90980f
#define OVKC_SEL_EDGE   1.00000f, 1.00000f, 1.00000f
#define OVKC_SEL_TEXT   0.09020f, 0.09020f, 0.10588f
#define OVKC_KEY_FACE   0.23529f, 0.23529f, 0.26667f
#define OVKC_KEY_EDGE   0.34118f, 0.34118f, 0.37255f
#define OVKC_KEY_LO     0.08235f, 0.08235f, 0.10196f
#define OVKC_FN_FACE    0.20000f, 0.20000f, 0.22745f
#define OVKC_DONE_FACE  0.34510f, 0.34510f, 0.38431f
#define OVKC_SHIFT_FACE 0.41569f, 0.41569f, 0.45490f
#define OVKC_BADGE_FACE 0.88627f, 0.88627f, 0.90980f
#define OVKC_BADGE_TEXT 0.09020f, 0.09020f, 0.10588f
#define OVKC_PILL_FACE  0.14118f, 0.14118f, 0.16863f
#define OVKC_PILL_EDGE  0.43529f, 0.43529f, 0.47059f
#define OVKC_PILL_TEXT  0.78824f, 0.78824f, 0.81176f
#define OVKC_CARET      1.00000f, 1.00000f, 1.00000f
#define OVK_PANEL 30, 34, 580, 396
#define OVK_BOX 56, 84, 528, 42
#define OVK_TITLE_POS 58, 46
#define OVK_COUNTER_Y 50
static const ovk_key_t ovk_letters[] = {
    { 44, 142, 48, 48, '1', '1', OVKA_CHAR, "1" },
    { 100, 142, 48, 48, '2', '2', OVKA_CHAR, "2" },
    { 156, 142, 48, 48, '3', '3', OVKA_CHAR, "3" },
    { 212, 142, 48, 48, '4', '4', OVKA_CHAR, "4" },
    { 268, 142, 48, 48, '5', '5', OVKA_CHAR, "5" },
    { 324, 142, 48, 48, '6', '6', OVKA_CHAR, "6" },
    { 380, 142, 48, 48, '7', '7', OVKA_CHAR, "7" },
    { 436, 142, 48, 48, '8', '8', OVKA_CHAR, "8" },
    { 492, 142, 48, 48, '9', '9', OVKA_CHAR, "9" },
    { 548, 142, 48, 48, '0', '0', OVKA_CHAR, "0" },
    { 44, 198, 48, 48, 'q', 'Q', OVKA_CHAR, "q" },
    { 100, 198, 48, 48, 'w', 'W', OVKA_CHAR, "w" },
    { 156, 198, 48, 48, 'e', 'E', OVKA_CHAR, "e" },
    { 212, 198, 48, 48, 'r', 'R', OVKA_CHAR, "r" },
    { 268, 198, 48, 48, 't', 'T', OVKA_CHAR, "t" },
    { 324, 198, 48, 48, 'y', 'Y', OVKA_CHAR, "y" },
    { 380, 198, 48, 48, 'u', 'U', OVKA_CHAR, "u" },
    { 436, 198, 48, 48, 'i', 'I', OVKA_CHAR, "i" },
    { 492, 198, 48, 48, 'o', 'O', OVKA_CHAR, "o" },
    { 548, 198, 48, 48, 'p', 'P', OVKA_CHAR, "p" },
    { 44, 254, 48, 48, 'a', 'A', OVKA_CHAR, "a" },
    { 100, 254, 48, 48, 's', 'S', OVKA_CHAR, "s" },
    { 156, 254, 48, 48, 'd', 'D', OVKA_CHAR, "d" },
    { 212, 254, 48, 48, 'f', 'F', OVKA_CHAR, "f" },
    { 268, 254, 48, 48, 'g', 'G', OVKA_CHAR, "g" },
    { 324, 254, 48, 48, 'h', 'H', OVKA_CHAR, "h" },
    { 380, 254, 48, 48, 'j', 'J', OVKA_CHAR, "j" },
    { 436, 254, 48, 48, 'k', 'K', OVKA_CHAR, "k" },
    { 492, 254, 48, 48, 'l', 'L', OVKA_CHAR, "l" },
    { 548, 254, 48, 48, '\'', '\'', OVKA_CHAR, "'" },
    { 44, 310, 48, 48, 'z', 'Z', OVKA_CHAR, "z" },
    { 100, 310, 48, 48, 'x', 'X', OVKA_CHAR, "x" },
    { 156, 310, 48, 48, 'c', 'C', OVKA_CHAR, "c" },
    { 212, 310, 48, 48, 'v', 'V', OVKA_CHAR, "v" },
    { 268, 310, 48, 48, 'b', 'B', OVKA_CHAR, "b" },
    { 324, 310, 48, 48, 'n', 'N', OVKA_CHAR, "n" },
    { 380, 310, 48, 48, 'm', 'M', OVKA_CHAR, "m" },
    { 436, 310, 48, 48, ',', ',', OVKA_CHAR, "," },
    { 492, 310, 48, 48, '.', '.', OVKA_CHAR, "." },
    { 548, 310, 48, 48, '-', '-', OVKA_CHAR, "-" },
};
static const ovk_key_t ovk_symbols[] = {
    { 44, 142, 48, 48, '1', '!', OVKA_CHAR, "1" },
    { 100, 142, 48, 48, '2', '@', OVKA_CHAR, "2" },
    { 156, 142, 48, 48, '3', '#', OVKA_CHAR, "3" },
    { 212, 142, 48, 48, '4', '$', OVKA_CHAR, "4" },
    { 268, 142, 48, 48, '5', '%', OVKA_CHAR, "5" },
    { 324, 142, 48, 48, '6', '^', OVKA_CHAR, "6" },
    { 380, 142, 48, 48, '7', '&', OVKA_CHAR, "7" },
    { 436, 142, 48, 48, '8', '*', OVKA_CHAR, "8" },
    { 492, 142, 48, 48, '9', '(', OVKA_CHAR, "9" },
    { 548, 142, 48, 48, '0', ')', OVKA_CHAR, "0" },
    { 44, 198, 48, 48, '-', '_', OVKA_CHAR, "-" },
    { 100, 198, 48, 48, '=', '+', OVKA_CHAR, "=" },
    { 156, 198, 48, 48, '[', '{', OVKA_CHAR, "[" },
    { 212, 198, 48, 48, ']', '}', OVKA_CHAR, "]" },
    { 268, 198, 48, 48, ';', ':', OVKA_CHAR, ";" },
    { 324, 198, 48, 48, '\'', '"', OVKA_CHAR, "'" },
    { 380, 198, 48, 48, ',', '<', OVKA_CHAR, "," },
    { 436, 198, 48, 48, '.', '>', OVKA_CHAR, "." },
    { 492, 198, 48, 48, '/', '?', OVKA_CHAR, "/" },
    { 548, 198, 48, 48, '\\', '|', OVKA_CHAR, "\\" },
    { 44, 254, 48, 48, '`', '~', OVKA_CHAR, "`" },
};
static const ovk_key_t ovk_func[] = {
    { 44, 366, 104, 48, '0', '0', OVKA_SHIFT, "Shift" },
    { 156, 366, 104, 48, '0', '0', OVKA_SYM, "#+=" },
    { 268, 366, 160, 48, '0', '0', OVKA_SPACE, "Space" },
    { 436, 366, 48, 48, '0', '0', OVKA_BKSP, "Del" },
    { 492, 366, 104, 48, '0', '0', OVKA_DONE, "Done" },
};
#define OVK_N_LETTERS 40
#define OVK_N_SYMBOLS 21
#define OVK_N_FUNC 5
