/* generated by tools/make_osk_font.py -- do not edit by hand */
enum { OVKA_CHAR, OVKA_SHIFT, OVKA_SYM, OVKA_SPACE, OVKA_BKSP, OVKA_DONE };
typedef struct { short x, y, w, h; char lo, hi; unsigned char act; const char *label; } ovk_key_t;
#define OVKC_PANEL_HI   0.34510f, 0.38431f, 0.50980f
#define OVKC_PANEL_LO   0.09020f, 0.10196f, 0.12941f
#define OVKC_TITLE_C    0.90980f, 0.92549f, 0.95686f
#define OVKC_DIM_C      0.60392f, 0.63922f, 0.70980f
#define OVKC_HINT_C     0.56078f, 0.59608f, 0.67059f
#define OVKC_BOX_BORDER 0.07843f, 0.09020f, 0.12549f
#define OVKC_BOX_FILL   0.10588f, 0.11765f, 0.14902f
#define OVKC_TEXT_C     0.95686f, 0.96471f, 0.98039f
#define OVKC_ACCENT     0.43137f, 0.65882f, 1.00000f
#define OVKC_SEL_FACE   0.23922f, 0.48235f, 1.00000f
#define OVKC_SEL_EDGE   0.61569f, 0.75686f, 1.00000f
#define OVKC_KEY_FACE   0.27059f, 0.30196f, 0.37647f
#define OVKC_KEY_EDGE   0.35686f, 0.39216f, 0.47451f
#define OVKC_KEY_LO     0.09020f, 0.10196f, 0.12941f
#define OVKC_FN_FACE    0.22745f, 0.25490f, 0.32157f
#define OVKC_DONE_FACE  0.18039f, 0.38824f, 0.78431f
#define OVKC_DONE_EDGE  0.43529f, 0.62353f, 0.90980f
#define OVKC_SHIFT_FACE 0.18431f, 0.36471f, 0.72157f
#define OVK_PANEL 30, 34, 580, 416
static const float ovk_bands[4][3] = { { 0.23137f, 0.26275f, 0.32549f }, { 0.20392f, 0.23137f, 0.28627f }, { 0.17647f, 0.20000f, 0.24706f }, { 0.14902f, 0.16863f, 0.20784f } };
#define OVK_BOX 56, 84, 528, 42
#define OVK_TITLE_POS 58, 46
#define OVK_COUNTER_Y 50
#define OVK_HINT_POS 60, 420
#define OVK_HINT "A TYPE  B DEL  X SHIFT  Y SPACE  L1/R1 PAGE  SEL CANCEL  START DONE"
static const ovk_key_t ovk_letters[] = {
    { 57, 142, 50, 48, '1', '1', OVKA_CHAR, "1" },
    { 110, 142, 50, 48, '2', '2', OVKA_CHAR, "2" },
    { 163, 142, 50, 48, '3', '3', OVKA_CHAR, "3" },
    { 216, 142, 50, 48, '4', '4', OVKA_CHAR, "4" },
    { 269, 142, 50, 48, '5', '5', OVKA_CHAR, "5" },
    { 322, 142, 50, 48, '6', '6', OVKA_CHAR, "6" },
    { 375, 142, 50, 48, '7', '7', OVKA_CHAR, "7" },
    { 428, 142, 50, 48, '8', '8', OVKA_CHAR, "8" },
    { 481, 142, 50, 48, '9', '9', OVKA_CHAR, "9" },
    { 534, 142, 50, 48, '0', '0', OVKA_CHAR, "0" },
    { 57, 198, 50, 48, 'q', 'Q', OVKA_CHAR, "q" },
    { 110, 198, 50, 48, 'w', 'W', OVKA_CHAR, "w" },
    { 163, 198, 50, 48, 'e', 'E', OVKA_CHAR, "e" },
    { 216, 198, 50, 48, 'r', 'R', OVKA_CHAR, "r" },
    { 269, 198, 50, 48, 't', 'T', OVKA_CHAR, "t" },
    { 322, 198, 50, 48, 'y', 'Y', OVKA_CHAR, "y" },
    { 375, 198, 50, 48, 'u', 'U', OVKA_CHAR, "u" },
    { 428, 198, 50, 48, 'i', 'I', OVKA_CHAR, "i" },
    { 481, 198, 50, 48, 'o', 'O', OVKA_CHAR, "o" },
    { 534, 198, 50, 48, 'p', 'P', OVKA_CHAR, "p" },
    { 57, 254, 50, 48, 'a', 'A', OVKA_CHAR, "a" },
    { 110, 254, 50, 48, 's', 'S', OVKA_CHAR, "s" },
    { 163, 254, 50, 48, 'd', 'D', OVKA_CHAR, "d" },
    { 216, 254, 50, 48, 'f', 'F', OVKA_CHAR, "f" },
    { 269, 254, 50, 48, 'g', 'G', OVKA_CHAR, "g" },
    { 322, 254, 50, 48, 'h', 'H', OVKA_CHAR, "h" },
    { 375, 254, 50, 48, 'j', 'J', OVKA_CHAR, "j" },
    { 428, 254, 50, 48, 'k', 'K', OVKA_CHAR, "k" },
    { 481, 254, 50, 48, 'l', 'L', OVKA_CHAR, "l" },
    { 57, 310, 50, 48, 'z', 'Z', OVKA_CHAR, "z" },
    { 110, 310, 50, 48, 'x', 'X', OVKA_CHAR, "x" },
    { 163, 310, 50, 48, 'c', 'C', OVKA_CHAR, "c" },
    { 216, 310, 50, 48, 'v', 'V', OVKA_CHAR, "v" },
    { 269, 310, 50, 48, 'b', 'B', OVKA_CHAR, "b" },
    { 322, 310, 50, 48, 'n', 'N', OVKA_CHAR, "n" },
    { 375, 310, 50, 48, 'm', 'M', OVKA_CHAR, "m" },
};
static const ovk_key_t ovk_symbols[] = {
    { 57, 142, 50, 48, '1', '1', OVKA_CHAR, "1" },
    { 110, 142, 50, 48, '2', '2', OVKA_CHAR, "2" },
    { 163, 142, 50, 48, '3', '3', OVKA_CHAR, "3" },
    { 216, 142, 50, 48, '4', '4', OVKA_CHAR, "4" },
    { 269, 142, 50, 48, '5', '5', OVKA_CHAR, "5" },
    { 322, 142, 50, 48, '6', '6', OVKA_CHAR, "6" },
    { 375, 142, 50, 48, '7', '7', OVKA_CHAR, "7" },
    { 428, 142, 50, 48, '8', '8', OVKA_CHAR, "8" },
    { 481, 142, 50, 48, '9', '9', OVKA_CHAR, "9" },
    { 534, 142, 50, 48, '0', '0', OVKA_CHAR, "0" },
    { 57, 198, 50, 48, '!', '!', OVKA_CHAR, "!" },
    { 110, 198, 50, 48, '@', '@', OVKA_CHAR, "@" },
    { 163, 198, 50, 48, '#', '#', OVKA_CHAR, "#" },
    { 216, 198, 50, 48, '$', '$', OVKA_CHAR, "$" },
    { 269, 198, 50, 48, '%', '%', OVKA_CHAR, "%" },
    { 322, 198, 50, 48, '^', '^', OVKA_CHAR, "^" },
    { 375, 198, 50, 48, '&', '&', OVKA_CHAR, "&" },
    { 428, 198, 50, 48, '*', '*', OVKA_CHAR, "*" },
    { 481, 198, 50, 48, '(', '(', OVKA_CHAR, "(" },
    { 534, 198, 50, 48, ')', ')', OVKA_CHAR, ")" },
    { 57, 254, 50, 48, '-', '-', OVKA_CHAR, "-" },
    { 110, 254, 50, 48, '_', '_', OVKA_CHAR, "_" },
    { 163, 254, 50, 48, '=', '=', OVKA_CHAR, "=" },
    { 216, 254, 50, 48, '+', '+', OVKA_CHAR, "+" },
    { 269, 254, 50, 48, '[', '[', OVKA_CHAR, "[" },
    { 322, 254, 50, 48, ']', ']', OVKA_CHAR, "]" },
    { 375, 254, 50, 48, '{', '{', OVKA_CHAR, "{" },
    { 428, 254, 50, 48, '}', '}', OVKA_CHAR, "}" },
    { 481, 254, 50, 48, ';', ';', OVKA_CHAR, ";" },
    { 534, 254, 50, 48, ':', ':', OVKA_CHAR, ":" },
    { 57, 310, 50, 48, '\'', '\'', OVKA_CHAR, "'" },
    { 110, 310, 50, 48, '"', '"', OVKA_CHAR, "\"" },
    { 163, 310, 50, 48, ',', ',', OVKA_CHAR, "," },
    { 216, 310, 50, 48, '.', '.', OVKA_CHAR, "." },
    { 269, 310, 50, 48, '/', '/', OVKA_CHAR, "/" },
    { 322, 310, 50, 48, '\\', '\\', OVKA_CHAR, "\\" },
    { 375, 310, 50, 48, '|', '|', OVKA_CHAR, "|" },
    { 428, 310, 50, 48, '~', '~', OVKA_CHAR, "~" },
    { 481, 310, 50, 48, '<', '<', OVKA_CHAR, "<" },
    { 534, 310, 50, 48, '>', '>', OVKA_CHAR, ">" },
};
static const ovk_key_t ovk_func[] = {
    { 60, 366, 86, 48, 0, 0, OVKA_SHIFT, "SHIFT" },
    { 149, 366, 66, 48, 0, 0, OVKA_SYM, "SYM" },
    { 218, 366, 180, 48, 0, 0, OVKA_SPACE, "SPACE" },
    { 401, 366, 66, 48, 0, 0, OVKA_BKSP, "DEL" },
    { 470, 366, 111, 48, 0, 0, OVKA_DONE, "DONE" },
};
#define OVK_N_LETTERS 36
#define OVK_N_SYMBOLS 40
#define OVK_N_FUNC 5
